# pubspec.yaml

name: library_api

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  shelf: any
  shelf_router: any
  mysql1: any
  dotenv: ^4.1.0
  dart_jsonwebtoken: any
  intl: any
  webdev: ^2.7.12

dev_dependencies:
  build_runner: any
  build_web_compilers: any
